northstar:
  message.endpoint: http://localhost:51888
  server.endpoint: http://localhost:8888
  
spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: DB_BAR_DATA

strategy-setting:
  demo-strategy:
    accountName: CTP-SimNow724
    strategyName: DemoStrategy
    mdContracts: cu2005,cu2006
    tdContracts: rb2005
  shadow-strategy:
    accountName: CTP-SimNow
    strategyName: ShadowStrategy
    mdContracts: rb2005,AP005,cu2005,IF2006,au2006
    tdContracts: rb2005
    followAccount: CTP-SimNow
    
    