server:
  port: 51888
  
northstar:
  endpoint: http://localhost:51666
  
spring:
    data:
        mongodb:
            host: 127.0.0.1
            port: 27017
            database: DB_BAR_DATA

strategy-setting:
  demo-strategy:
    gatewayName: 默认CTP账户
    name: DemoStrategy
    mdContracts: rb2005
    tdContracts: rb2005
    
    
    